name: ci runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'ubuntu'
          java-version: '11'

      - name: Run Maven Install
        run: make install

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: reports
